[project]
authors = ["Jacob Williams <jacobwilliams@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "env"
platforms = ["osx-arm64", "win-64", "linux-64"]
version = "2.1.0"

[tasks]
viewer = "python hdf5_viewer.py"


[dependencies]
python = ">=3.14.0,<3.15"
h5py = ">=3.15.1,<4"
pyside6 = ">=6.9.3,<7"
numpy = ">=2.3.5,<3"
qtpy = ">=2.4.3,<3"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.7,<4"
pytest = ">=9.0.0,<10"
ruff = ">=0.14.4,<0.15"
pylint = ">=4.0.2,<5"
sphinx-autobuild = ">=2025.8.25,<2026"
sphinx = ">=8.2.3,<9"
sphinx-rtd-theme = ">=3.0.2,<4"
python-build = ">=1.3.0,<2"
pyinstaller = ">=6.16.0,<7"
setuptools = ">=80.9.0,<81"
wheel = ">=0.45.1,<0.46"
hatch = ">=1.14.1,<2"
grayskull = ">=2.9.1,<3"
tabulate = ">=0.9.0,<0.10"
openpyxl = ">=3.1.5,<4"
python-graphviz = ">=0.21,<0.22"
pyqtgraph = ">=0.14.0,<0.15"
networkx = ">=3.6,<4"
scipy = ">=1.16.3,<2"
pydot = ">=4.0.1,<5"
pygraphviz = ">=1.14,<2"
